# Generated by Django 6.0 on 2026-07-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='highlights',
            field=models.TextField(blank=True),
        ),
    ]
